#!/bin/sh

# stash any unstaged or untracked changes
git stash -q --keep-index --include-untracked

# run the tests with the gradle wrapper
./gradlew check

# store the last exit code in a variable
RESULT=$?

# unstash the unstashed changes
git stash pop -q

# return the './gradlew test' exit code
exit $RESULT
